FROM rocm/pytorch
LABEL maintainer="prime intellect"
LABEL repository="prime-rl"

# install python and dependencies
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-venv \
    python3-dev \
    build-essential \
    git
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# setup app environment
WORKDIR /app
COPY ./pyproject.toml ./pyproject.toml
COPY ./uv.lock ./uv.lock
COPY ./README.md ./README.md
COPY ./src/ ./src/
COPY ./configs/ ./configs/

# install project dependencies
RUN python3 -m venv ./venv
RUN ./venv/bin/pip install --no-cache-dir .

# uninstall all nvidia-related packages (torch, triton, cuda, etc.)
RUN ./venv/bin/pip uninstall -y \
    nvidia-cuda-runtime-cu12 \
    nvidia-cuda-nvrtc-cu12 \
    nvidia-cuda-nvrtc-dev \
    nvidia-cudnn-cu12 \
    nvidia-cublas-cu12 \
    nvidia-cufft-cu12 \
    nvidia-curand-cu12 \
    nvidia-cusolver-cu12 \
    nvidia-cusparse-cu12 \
    nvidia-nccl-cu12 \
    nvidia-nvtx-cu12 \
    torch \
    triton

# uninstall vllm
RUN ./venv/bin/pip uninstall -y vllm

# install ROCm packages
RUN ./venv/bin/pip install --no-cache-dir --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/rocm6.3

# install vllm dependencies
RUN ./venv/bin/pip install --upgrade --no-cache-dir aiter amdsmi numba scipy huggingface-hub[cli,hf_transfer] setuptools_scm "numpy<2"

# clone vllm repository
RUN git clone https://github.com/vllm-project/vllm.git

# install vllm
WORKDIR /app/vllm

ENV PYTORCH_ROCM_ARCH="gfx90a;gfx942"
RUN ../venv/bin/pip install --no-cache-dir -r requirements/rocm.txt
RUN ../venv/bin/python setup.py develop

# entry point for zeroband
WORKDIR /app
ENV PATH="/app/venv/bin:$PATH"
ENTRYPOINT ["python", "src/zeroband/infer.py"]