model_name = "Qwen/Qwen2.5-Coder-1.5B"
dataset = "data/swe_smith_proper"
batch_size = 8
dp = 6
rollout_path = "swe_bench_rollouts"
output_path = "swe_bench_outputs"
clean_output_path = true
max_model_len = 8192

[sampling]
temperature = 0.7
max_tokens = 1024
top_p = 0.95
n = 8